# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-bridge","commands":[{"id":"agent-bridge","relativePath":"bin/agent-bridge","purpose":"Communicate with persistent agent sessions"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: 37b2ac4d46f6abc2d1ea19da49852ed101f61e9ee32e0bdcbad643d78cca6187
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$commandPath = Join-Path $selfRoot 'bin\agent-bridge.cmd'
$installerPath = Join-Path $selfRoot 'scripts\install.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-bridge'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-bridge'
            argv = @($commandPath)
            shell = 'cmd'
            purpose = 'Communicate with persistent agent sessions'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-bridge session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
