# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-pull-requests","commands":[{"id":"agent-pull-requests","relativePath":"bin/agent-pull-requests","purpose":"Read and later drive cross-repository pull request state"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: e19d537cb9443cea297481097f04a85f007fd242eb00825914a6802d859c520d
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$commandPath = Join-Path $selfRoot 'bin\agent-pull-requests.cmd'
$installerPath = Join-Path $selfRoot 'scripts\install.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-pull-requests'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-pull-requests'
            argv = @($commandPath)
            shell = 'cmd'
            purpose = 'Read and later drive cross-repository pull request state'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-pull-requests session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
