# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-vault","commands":[{"id":"agent-vault","relativePath":"bin/agent-vault","purpose":"Fetch and manage machine-local vault credentials"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: cc2c63f359a999278e1db70c16365fb5abae47ed805f442a7d0af46b0f814ca8
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$contextRoot = if ($env:COPILOT_PLUGIN_ROOT) { $env:COPILOT_PLUGIN_ROOT } else { $selfRoot }
try { $contextRoot = (Resolve-Path $contextRoot).Path } catch { Write-Output '{}'; exit 0 }
if (-not [StringComparer]::OrdinalIgnoreCase.Equals($contextRoot, $selfRoot)) {
    Write-Output '{}'
    exit 0
}

$commandPath = Join-Path $selfRoot 'bin\agent-vault.cmd'
$installerPath = Join-Path $selfRoot 'scripts\install.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-vault'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-vault'
            argv = @($commandPath)
            shell = 'cmd'
            purpose = 'Fetch and manage machine-local vault credentials'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-vault session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
