#!/usr/bin/env python3
"""Bind a stateless harness to its knowledge repo -- the machine-local half.

This is the mechanical, idempotent core of the harness-first setup flow (see the
``binding-knowledge`` skill, which orchestrates the interactive ask + repo
creation/cloning/registration and then calls this). It writes ONLY machine-local
state, so the shareable harness tree stays generic and name-free:

  1. ``~/.<harness>/config.yaml`` -> set the top-level ``knowledge_repo: <name>``
     pointer (the seam the state-root resolver reads), preserving the rest of the
     file (comments included).
  2. ``~/.<harness>/.github/instructions/knowledge-binding.instructions.md`` -> a
     managed instructions fragment (loaded via ``COPILOT_CUSTOM_INSTRUCTIONS_DIRS``)
     that LABELS the concrete repos + paths for THIS machine -- harness at X,
     knowledge at Y, plus any coordinated product repos.

It never writes into the harness checkout and never touches the committed
``related.yaml`` (that would leak a repo name into the shareable tree). Pure +
idempotent; safe to re-run.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MANAGED_MARKER = "<!-- managed by harness-knowledge -->"


def set_top_yaml_key(text: str, key: str, value: str) -> str:
    """Replace or insert a top-level ``key: value`` line, preserving the rest.

    Line-based (not a YAML round-trip) so comments and formatting survive. If the
    key already exists at column 0, its line is replaced; otherwise the pair is
    inserted after any leading comment/blank block (so it lands near the top,
    below the file header).
    """
    line = f"{key}: {value}"
    pat = re.compile(rf"^{re.escape(key)}\s*:.*$", re.MULTILINE)
    if pat.search(text):
        return pat.sub(line, text, count=1)

    lines = text.splitlines()
    insert_at = 0
    for i, ln in enumerate(lines):
        s = ln.strip()
        if s == "" or s.startswith("#"):
            insert_at = i + 1
            continue
        break
    lines.insert(insert_at, line)
    out = "\n".join(lines)
    if text.endswith("\n") and not out.endswith("\n"):
        out += "\n"
    return out


def render_instructions(
    harness: str,
    harness_path: str,
    knowledge: str,
    knowledge_path: str,
    product_repos: list[tuple[str, str]] | None = None,
) -> str:
    """Render the machine-local knowledge-binding instructions fragment."""
    rows = [
        f"| **harness** (this control plane, stateless) | `{harness}` | `{harness_path}` |",
        f"| **knowledge** (your private state home) | `{knowledge}` | `{knowledge_path}` |",
    ]
    for name, path in (product_repos or []):
        rows.append(f"| product / coordinated | `{name}` | `{path}` |")
    table = "\n".join(rows)
    return f"""{MANAGED_MARKER}
# Knowledge binding (this machine)

This machine binds the **stateless harness** `{harness}` to your private
**knowledge** repo `{knowledge}`. These concrete names/paths live here (machine-local,
loaded via `COPILOT_CUSTOM_INSTRUCTIONS_DIRS`) and are **never committed** into the
shareable harness tree.

| Repo | Name | Path (this machine) |
|------|------|---------------------|
{table}

**Routing (see the harness AGENTS.md for the full rule):** personal state --
efforts, logs, weekly-updates, personal visions, notes, artifacts, "memory", and
any rootless/ambiguous write -- defaults to the **knowledge** repo (`{knowledge}`),
never the harness. Resolve the destination with `agent-worktrees state-root`.
Edits to the **harness** or its plugins are the *explicit* case (a named
behavior/skill/agent/doc). This binding is regenerated by the `harness-knowledge`
plugin; do not hand-edit.
"""


def bind(
    harness: str,
    knowledge: str,
    knowledge_path: str,
    *,
    home: Path,
    harness_path: str = "",
    product_repos: list[tuple[str, str]] | None = None,
    assemble_plugins: bool = True,
) -> dict:
    """Write the machine-local binding. Idempotent. Returns a summary dict."""
    base = Path(home) / f".{harness}"
    base.mkdir(parents=True, exist_ok=True)

    cfg = base / "config.yaml"
    existing = cfg.read_text(encoding="utf-8") if cfg.exists() else ""
    if not existing.strip():
        existing = f"# Machine-local config for {harness} (harness-knowledge managed pointer).\nrepo_name: {harness}\n"
    updated = set_top_yaml_key(existing, "knowledge_repo", knowledge)
    cfg.write_text(updated, encoding="utf-8")

    instr_dir = base / ".github" / "instructions"
    instr_dir.mkdir(parents=True, exist_ok=True)
    frag = instr_dir / "knowledge-binding.instructions.md"
    frag.write_text(
        render_instructions(
            harness, harness_path or f"<{harness} checkout>",
            knowledge, knowledge_path, product_repos,
        ),
        encoding="utf-8",
    )

    summary = {
        "harness": harness,
        "knowledge_repo": knowledge,
        "knowledge_path": knowledge_path,
        "config": str(cfg),
        "instructions": str(frag),
    }

    # #955: assemble the harness's personal-plugin overlay from the knowledge
    # repo's .ai local marketplace(s), so the operator's personal skills/agents
    # load in the name-free harness. Best-effort: a missing/plugin-less knowledge
    # checkout just yields no overlay; never fails the bind.
    if assemble_plugins and harness_path and knowledge_path:
        try:
            from assemble_plugins import assemble
        except ImportError:
            import importlib.util as _ilu
            _p = Path(__file__).resolve().parent / "assemble_plugins.py"
            _spec = _ilu.spec_from_file_location("assemble_plugins", _p)
            _mod = _ilu.module_from_spec(_spec)
            _spec.loader.exec_module(_mod)
            assemble = _mod.assemble
        try:
            summary["plugins"] = assemble(harness_path, knowledge_path)
        except Exception as exc:  # noqa: BLE001 -- never fail the bind on plugin assembly
            summary["plugins_error"] = str(exc)

    return summary


def _parse_products(items: list[str] | None) -> list[tuple[str, str]]:
    out = []
    for it in items or []:
        if "=" in it:
            name, path = it.split("=", 1)
            out.append((name.strip(), path.strip()))
    return out


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="bind_knowledge",
        description="Write the machine-local harness<->knowledge binding (idempotent).",
    )
    p.add_argument("--harness", required=True, help="The stateless harness repo name (e.g. citadel-harness).")
    p.add_argument("--knowledge", required=True, help="The knowledge repo name.")
    p.add_argument("--knowledge-path", default="", help="Local checkout path of the knowledge repo.")
    p.add_argument("--harness-path", default="", help="Local checkout path of the harness (for the label).")
    p.add_argument("--product", action="append", default=[], metavar="name=path",
                   help="A coordinated product repo to label (repeatable).")
    p.add_argument("--home", default=str(Path.home()), help="Home dir override (testing).")
    p.add_argument("--json", action="store_true", help="Emit the summary as JSON.")
    args = p.parse_args(argv)

    summary = bind(
        args.harness, args.knowledge, args.knowledge_path,
        home=Path(args.home), harness_path=args.harness_path,
        product_repos=_parse_products(args.product),
    )
    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print(f"Bound {args.harness} -> knowledge_repo: {args.knowledge}")
        print(f"  pointer:      {summary['config']}")
        print(f"  instructions: {summary['instructions']}")
        print("Next: register the knowledge repo so state-root can resolve it, e.g.")
        print(f"  agent-worktrees repos add {args.knowledge} \"{args.knowledge_path or '<path>'}\" --class singleton")
        print("Verify: agent-worktrees state-root --json  (expect requires_external + the knowledge path)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
