# Generated by libs/payload-invocation/generate.py. Do not edit.
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$contextRoot = if ($env:COPILOT_PLUGIN_ROOT) { $env:COPILOT_PLUGIN_ROOT } else { $selfRoot }
try { $contextRoot = (Resolve-Path $contextRoot).Path } catch { Write-Output '{}'; exit 0 }
if (-not [StringComparer]::OrdinalIgnoreCase.Equals($contextRoot, $selfRoot)) {
    Write-Output '{}'
    exit 0
}

$catalogShim = 'powershell'
$hostPath = ''
$losslessNativeArguments = (
    $PSVersionTable.PSEdition -eq 'Core' -and
    $PSVersionTable.PSVersion -ge [Version]'7.3'
)
if ($catalogShim -eq 'powershell' -and $losslessNativeArguments) {
    try { $hostPath = (Get-Process -Id $PID).Path } catch {}
    if (-not ($hostPath -and [IO.Path]::IsPathRooted($hostPath))) {
        $hostPath = ''
    }
}
$installerPath = Join-Path $selfRoot 'scripts\init.ps1'
$specs = '[{"id":"agent-mcp","relativePath":"bin\\agent-mcp.ps1","purpose":"Wrap authenticate and materialize MCP servers"}]' | ConvertFrom-Json
$commands = @(
    foreach ($spec in @($specs)) {
        $commandPath = Join-Path $selfRoot ([string]$spec.relativePath)
        $entrypointReady = Test-Path -LiteralPath $commandPath
        $argv = if ($catalogShim -eq 'powershell' -and $hostPath) {
            @(
                $hostPath,
                '-NoProfile',
                '-ExecutionPolicy',
                'Bypass',
                '-File',
                $commandPath
            )
        } else {
            @($commandPath)
        }
        $availability = if (
            $entrypointReady -and
            (Test-Path -LiteralPath $installerPath) -and
            ($catalogShim -ne 'powershell' -or $hostPath)
        ) { 'ready' } else { 'unavailable' }
        [ordered]@{
            id = [string]$spec.id
            argv = [object[]]@($argv)
            shell = if ($catalogShim -eq 'powershell') {
                if ($hostPath) { 'direct' } else { 'powershell' }
            } else {
                'direct'
            }
            purpose = [string]$spec.purpose
            availability = $availability
        }
    }
)
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-mcp'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = $commands
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-mcp session command catalog'
    ''
    'Select a command by `id` and append arguments to its exact `argv` prefix. Quote each prefix element separately when rendering a shell command; prepend `&` in PowerShell. Never substitute a global or `PATH` binstub for any prefix element.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
$envelope = @{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3

$sessionId = ''
if ([Console]::IsInputRedirected) {
    $hookInput = [Console]::In.ReadToEnd()
    if ($hookInput) {
        try {
            $hookPayload = $hookInput | ConvertFrom-Json
            if ($hookPayload.sessionId -is [string]) {
                $sessionId = $hookPayload.sessionId
            } elseif ($hookPayload.session_id -is [string]) {
                $sessionId = $hookPayload.session_id
            }
        } catch {
            [Console]::Error.WriteLine(
                '[agent-mcp] invalid sessionStart payload; catalog deduplication disabled: ' +
                $_.Exception.Message
            )
        }
    }
}

$launchToken = ''
try {
    if (
        $env:OS -eq 'Windows_NT' -or
        (Get-Variable IsWindows -ErrorAction SilentlyContinue).Value
    ) {
        $currentProcess = Get-Process -Id $PID -ErrorAction Stop
        if (
            $currentProcess.PSObject.Properties['Parent'] -and
            $currentProcess.Parent
        ) {
            $launcherPid = [int]$currentProcess.Parent.Id
        } else {
            $processInfo = Get-CimInstance Win32_Process -Filter "ProcessId = $PID"
            $launcherPid = [int]$processInfo.ParentProcessId
        }
    } else {
        $launcherPid = [int](
            & ps -o ppid= -p $PID 2>$null
        ).Trim()
    }
    $launcher = Get-Process -Id $launcherPid -ErrorAction Stop
    $launchToken = '{0}:{1}' -f $launcherPid, (
        $launcher.StartTime.ToUniversalTime().Ticks
    )
} catch {
    [Console]::Error.WriteLine(
        '[agent-mcp] catalog deduplication launch identity unavailable: ' +
        $_.Exception.Message
    )
}

$markerPath = ''
if ($sessionId -and $launchToken) {
    $hashAlgorithm = [Security.Cryptography.SHA256]::Create()
    try {
        $markerBytes = [Text.Encoding]::UTF8.GetBytes(
            $launchToken + [char]0 + $sessionId + [char]0 + $catalogJson
        )
        $markerKey = [BitConverter]::ToString(
            $hashAlgorithm.ComputeHash($markerBytes)
        ).Replace('-', '').ToLowerInvariant()
    } finally {
        $hashAlgorithm.Dispose()
    }
    $markerBase = if (
        $env:OS -eq 'Windows_NT' -or
        (Get-Variable IsWindows -ErrorAction SilentlyContinue).Value
    ) {
        [IO.Path]::GetTempPath()
    } else {
        Join-Path $HOME '.cache'
    }
    $markerRoot = Join-Path $markerBase 'copilot-extensions-session-command-catalog'
    $markerPath = Join-Path $markerRoot $markerKey
    try {
        [void][IO.Directory]::CreateDirectory($markerRoot)
        try {
            $markers = @(
                Get-ChildItem -LiteralPath $markerRoot -File |
                    Sort-Object LastWriteTimeUtc
            )
            if ($markers.Count -ge 2048) {
                $markers |
                    Select-Object -First ($markers.Count - 2047) |
                    Remove-Item -Force -ErrorAction SilentlyContinue
            }
        } catch {}
        $marker = [IO.File]::Open(
            $markerPath,
            [IO.FileMode]::CreateNew,
            [IO.FileAccess]::Write,
            [IO.FileShare]::None
        )
        $marker.Dispose()
    } catch [IO.IOException] {
        if (Test-Path -LiteralPath $markerPath) {
            [Console]::Out.WriteLine('{}')
            exit 0
        }
        $markerPath = ''
        [Console]::Error.WriteLine(
            '[agent-mcp] catalog deduplication unavailable: ' +
            $_.Exception.Message
        )
    } catch {
        $markerPath = ''
        [Console]::Error.WriteLine(
            '[agent-mcp] catalog deduplication unavailable: ' +
            $_.Exception.Message
        )
    }
}

try {
    [Console]::Out.WriteLine($envelope)
} catch {
    if ($markerPath) {
        Remove-Item -LiteralPath $markerPath -Force -ErrorAction SilentlyContinue
    }
    exit 0
}
exit 0
