# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-mcp","commands":[{"id":"agent-mcp","relativePath":"bin/agent-mcp","purpose":"Wrap authenticate and materialize MCP servers"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: b8fe3d0734c50974ecb0df642725bb02fa5c600dfe2c3863d5c52709a2a59d0f
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$commandPath = Join-Path $selfRoot 'bin\agent-mcp.cmd'
$installerPath = Join-Path $selfRoot 'scripts\init.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-mcp'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-mcp'
            argv = @($commandPath)
            shell = 'cmd'
            purpose = 'Wrap authenticate and materialize MCP servers'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-mcp session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
