#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"budget-guidance","commands":[{"id":"budget-guidance","relativePath":"bin/budget-guidance","purpose":"Report current attributable budget posture"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 38eccd9a8aa68161e5dbf91aa6bcb1a376098903028b433855c2efc33b27b2f8
set -eu

json_escape() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\r'/\\r}"
    value="${value//$'\n'/\\n}"
    value="${value//$'\t'/\\t}"
    printf '%s' "$value"
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"
context_root="${COPILOT_PLUGIN_ROOT:-$self_root}"
context_root="$(cd "$context_root" 2>/dev/null && pwd -P)" || {
    printf '%s\n' '{}'
    exit 0
}
[ "$context_root" = "$self_root" ] || {
    printf '%s\n' '{}'
    exit 0
}

command_path="$self_root/bin/budget-guidance"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"

catalog="{\"schema\":\"copilot-extensions.session-command-catalog\",\"version\":1,\"plugin\":\"budget-guidance\",\"payload\":{\"provenance\":\"payload-local\"},\"commands\":[{\"id\":\"budget-guidance\",\"argv\":[\"$(json_escape "$command_path")\"],\"shell\":\"direct\",\"purpose\":\"Report current attributable budget posture\",\"availability\":\"$availability\"}]}"
context="## budget-guidance session command catalog

Invoke the exact \`argv\` below. Do not search \`PATH\` or substitute a same-named command from another payload.

\`\`\`json
$catalog
\`\`\`"
printf '{"additionalContext":"%s"}\n' "$(json_escape "$context")"
