# Generated by libs/payload-invocation/generate.py. Do not edit.
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$contextRoot = if ($env:COPILOT_PLUGIN_ROOT) { $env:COPILOT_PLUGIN_ROOT } else { $selfRoot }
try { $contextRoot = (Resolve-Path $contextRoot).Path } catch { Write-Output '{}'; exit 0 }
if (-not [StringComparer]::OrdinalIgnoreCase.Equals($contextRoot, $selfRoot)) {
    Write-Output '{}'
    exit 0
}

$installerPath = Join-Path $selfRoot 'scripts\install.ps1'
$specs = '[{"id":"agent-logger","relativePath":"bin\\agent-logger.ps1","purpose":"Inspect agent logger configuration and chronicle state"},{"id":"collate-session","relativePath":"bin\\collate-session.ps1","purpose":"Collate one Copilot session into digest segments"},{"id":"read-session-digest","relativePath":"bin\\read-session-digest.ps1","purpose":"Read collated session digest data"},{"id":"prepare-session-log","relativePath":"bin\\prepare-session-log.ps1","purpose":"Prepare one session log manifest and output path"},{"id":"ramp-up-session","relativePath":"bin\\ramp-up-session.ps1","purpose":"Build a bounded takeover briefing for a dormant session"},{"id":"session-sync","relativePath":"bin\\session-sync.ps1","purpose":"Sync archive and compact Copilot session data"}]' | ConvertFrom-Json
$commands = @(
    foreach ($spec in @($specs)) {
        $commandPath = Join-Path $selfRoot ([string]$spec.relativePath)
        $availability = if (
            (Test-Path -LiteralPath $commandPath) -and
            (Test-Path -LiteralPath $installerPath)
        ) { 'ready' } else { 'unavailable' }
        [ordered]@{
            id = [string]$spec.id
            argv = @($commandPath)
            shell = 'direct'
            purpose = [string]$spec.purpose
            availability = $availability
        }
    }
)
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-logger'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = $commands
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-logger session command catalog'
    ''
    'Select the command by `id` and invoke its exact `argv`. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
