#!/usr/bin/env python3
"""Phase 4 of the dev-branch-release-pipeline effort
(ThomasMichon/copilot-extensions#3336): emergency rollback for a bad
promotion generated by ``tools/promote_release.py``.

Operator flow for a bad promotion (the stated rollback procedure this tool
implements):

1. **Pause first.** ``python tools/rollback_release.py pause --reason "..."
   --push`` -- lands a small commit on ``main`` marking the pipeline paused
   *before* the rollback commit itself lands, so a promotion cannot race the
   rollback. ``.github/workflows/promote.yml`` refuses to run (via
   ``tools/promote_release.py``'s own pause check) while this is set.
2. **Revert.** ``python tools/rollback_release.py revert --reason "..."
   --push`` -- ``git revert``s the most recent promotion commit (refusing
   to touch anything else -- see the guard below), tags it, and records the
   rollback in the pipeline state so a subsequent promotion of that exact
   `dev` state is refused (the non-incremental-update guard) until `dev`
   actually moves forward with a fix.
3. **Fix forward on `dev`**, then **resume**:
   ``python tools/rollback_release.py resume --push``.

Guards:

* ``revert`` only ever reverts the commit ``main``'s tip actually *is*, and
  only when the pipeline state confirms it is the most recently generated
  promotion commit -- never an arbitrary older commit, which would produce
  a confusing, out-of-order rollback.
* A subsequent ``promote_release.py`` run refuses to re-promote the exact
  `dev` state that was just rolled back, unless the operator passes
  ``--force`` -- this is the "CI guard against a non-incremental update
  after a manual rollback" from the effort's Phase 4 checklist.

Usage::

    python tools/rollback_release.py status
    python tools/rollback_release.py pause --reason "bad promotion, investigating" --push
    python tools/rollback_release.py revert --reason "..." --push
    python tools/rollback_release.py resume --push
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from promote_release import (  # noqa: E402
    PIPELINE_STATE_PATH,
    PromotionError,
    _git,
    _read_pipeline_state,
    _rev_parse,
    add_scratch_worktree,
    remove_scratch_worktree,
)

REPO = Path(__file__).resolve().parent.parent


def _write_state_commit(
    *, repo: Path, main_ref: str, state: dict, message: str, push: bool
) -> dict:
    """Land ``state`` as a small, real commit on ``main`` (never touching
    any other file) via an isolated scratch worktree."""
    import json

    main_head = _rev_parse(main_ref, cwd=repo)
    if main_head is None:
        raise PromotionError(f"cannot resolve main ref: {main_ref!r}")

    scratch = add_scratch_worktree(main_head, repo=repo)
    try:
        path = scratch / PIPELINE_STATE_PATH
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        _git(["add", PIPELINE_STATE_PATH], cwd=scratch)
        _git(["-c", "user.name=copilot-extensions-release-bot",
              "-c", "user.email=release-bot@users.noreply.github.com",
              "commit", "-m", message], cwd=scratch)
        commit = _git(["rev-parse", "HEAD"], cwd=scratch)
        if push:
            _git(["push", "origin", f"{commit}:refs/heads/main"], cwd=scratch)
        return {"commit": commit, "main_before": main_head, "pushed": push}
    finally:
        remove_scratch_worktree(scratch, repo=repo)


def cmd_status(args: argparse.Namespace) -> int:
    main_head = _rev_parse(args.main_ref, cwd=args.repo)
    if main_head is None:
        print(f"rollback-release: cannot resolve main ref: {args.main_ref!r}", file=sys.stderr)
        return 1
    state = _read_pipeline_state(main_head, repo=args.repo)
    print(f"main: {main_head}")
    print(f"paused: {state.get('paused')}")
    if state.get("paused"):
        print(f"  reason: {state.get('pause_reason')}")
    last_promotion = state.get("last_promotion")
    print(f"last_promotion: {last_promotion}")
    last_rollback = state.get("last_rollback")
    print(f"last_rollback: {last_rollback}")
    return 0


def pause(*, repo: Path = REPO, main_ref: str = "origin/main", reason: str, push: bool) -> dict:
    main_head = _rev_parse(main_ref, cwd=repo)
    if main_head is None:
        raise PromotionError(f"cannot resolve main ref: {main_ref!r}")
    state = _read_pipeline_state(main_head, repo=repo)
    state["paused"] = True
    state["pause_reason"] = reason
    return _write_state_commit(
        repo=repo, main_ref=main_ref, state=state,
        message=f"release-pipeline: pause promotion -- {reason}",
        push=push,
    )


def resume(*, repo: Path = REPO, main_ref: str = "origin/main", push: bool) -> dict:
    main_head = _rev_parse(main_ref, cwd=repo)
    if main_head is None:
        raise PromotionError(f"cannot resolve main ref: {main_ref!r}")
    state = _read_pipeline_state(main_head, repo=repo)
    state["paused"] = False
    state["pause_reason"] = None
    return _write_state_commit(
        repo=repo, main_ref=main_ref, state=state,
        message="release-pipeline: resume promotion",
        push=push,
    )


def cmd_pause(args: argparse.Namespace) -> int:
    try:
        result = pause(repo=args.repo, main_ref=args.main_ref, reason=args.reason, push=args.push)
    except PromotionError as exc:
        print(f"rollback-release: {exc}", file=sys.stderr)
        return 1
    print(f"rollback-release: paused (commit {result['commit']})")
    if not result["pushed"]:
        print("  (not pushed -- re-run with --push to make this take effect on origin/main)")
    return 0


def cmd_resume(args: argparse.Namespace) -> int:
    try:
        result = resume(repo=args.repo, main_ref=args.main_ref, push=args.push)
    except PromotionError as exc:
        print(f"rollback-release: {exc}", file=sys.stderr)
        return 1
    print(f"rollback-release: resumed (commit {result['commit']})")
    if not result["pushed"]:
        print("  (not pushed -- re-run with --push to make this take effect on origin/main)")
    return 0


def _find_last_promotion_commit(main_head: str, *, repo: Path) -> str | None:
    """Walk ``main_head``'s history for the most recent commit tagged as a
    generated promotion (a "promote-" tag pointing at it) -- so ``revert``
    can find the right commit to undo even when a pause/resume bookkeeping
    commit has landed on top of it since (the real operator flow is
    "pause, THEN revert", so main's literal tip is often not the
    promotion commit itself by the time revert runs)."""
    history = _git(["log", "--format=%H", main_head], cwd=repo).splitlines()
    for sha in history:
        tags = _git(["tag", "--points-at", sha], cwd=repo).splitlines()
        if any(tag.startswith("promote-") for tag in tags):
            return sha
    return None


def _tree_with_state_overlay(base_tree: str, state: dict, *, repo: Path) -> str:
    """Return a tree identical to ``base_tree`` except with
    ``PIPELINE_STATE_PATH`` set to ``state`` -- pure git plumbing (a
    throwaway index), so this never depends on or conflicts with whatever
    a real working tree/checkout currently looks like."""
    import json
    import os
    import subprocess as _subprocess
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        index_file = Path(tmp) / "index"
        env = {**os.environ, "GIT_INDEX_FILE": str(index_file)}
        _subprocess.run(
            ["git", "read-tree", base_tree], cwd=str(repo), env=env,
            check=True, capture_output=True,
        )
        blob = _subprocess.run(
            ["git", "hash-object", "-w", "--stdin"], cwd=str(repo), env=env,
            input=json.dumps(state, indent=2, sort_keys=True) + "\n",
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        _subprocess.run(
            ["git", "update-index", "--add", "--cacheinfo",
             f"100644,{blob},{PIPELINE_STATE_PATH}"],
            cwd=str(repo), env=env, check=True, capture_output=True,
        )
        result = _subprocess.run(
            ["git", "write-tree"], cwd=str(repo), env=env,
            capture_output=True, text=True, check=True,
        )
        return result.stdout.strip()


def revert(*, repo: Path = REPO, main_ref: str = "origin/main", reason: str, push: bool) -> dict:
    main_head = _rev_parse(main_ref, cwd=repo)
    if main_head is None:
        raise PromotionError(f"cannot resolve main ref: {main_ref!r}")
    state = _read_pipeline_state(main_head, repo=repo)
    last_promotion = state.get("last_promotion")
    if not last_promotion:
        raise PromotionError(
            "no recorded promotion to roll back (pipeline state has no last_promotion)"
        )
    # The commit being reverted must itself be a generated promotion commit
    # (a tag with the "promote-" prefix must point at it) -- never revert an
    # arbitrary older or hand-pushed commit, which would produce a
    # confusing, out-of-order rollback. This is the guard the effort's
    # Phase 4 checklist calls for, implemented without needing the
    # promotion's own commit sha stored in its own state (a self-referential
    # value that can't exist -- a commit's hash depends on its tree, which
    # would depend on that same value).
    promotion_commit = _find_last_promotion_commit(main_head, repo=repo)
    if promotion_commit is None:
        raise PromotionError(
            f"no generated promotion commit found in {main_ref}'s history "
            "-- refusing to revert an unrecognized state"
        )

    # Restore the promotion commit's PARENT tree wholesale (the same
    # wholesale-tree-replace philosophy promote_release.py itself uses,
    # rather than `git revert`'s content-diff/three-way-merge machinery --
    # which would conflict here whenever a pause/resume bookkeeping commit
    # landed on top and touched the very same state-file path the
    # promotion commit also touched), then overlay our own updated
    # rollback state on top of that restored tree.
    pre_promotion_commit = _git(["rev-parse", f"{promotion_commit}^"], cwd=repo)
    pre_promotion_tree = _git(["rev-parse", f"{pre_promotion_commit}^{{tree}}"], cwd=repo)

    state["last_rollback"] = {
        "reverted_commit": promotion_commit,
        "reverted_dev_head": last_promotion.get("dev_head"),
        "reason": reason,
        "at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    new_tree = _tree_with_state_overlay(pre_promotion_tree, state, repo=repo)

    message = (
        f"release-pipeline: rollback -- revert {promotion_commit[:12]} "
        f"({reason})\n\nThis is a generated revert commit (never a "
        "force-push/history-rewrite): main's tree is restored to its "
        f"pre-promotion state (parent of {promotion_commit[:12]}), with "
        "main's own tip as this commit's sole parent.\n"
    )
    revert_commit = _git(
        ["commit-tree", new_tree, "-p", main_head, "-m", message], cwd=repo
    )
    tag_name = f"rollback-{time.strftime('%Y%m%d%H%M%S')}-{revert_commit[:8]}"
    _git(["tag", "-a", tag_name, "-m", message, revert_commit], cwd=repo)

    if push:
        _git(["push", "origin", f"{revert_commit}:refs/heads/main"], cwd=repo)
        _git(["push", "origin", tag_name], cwd=repo)

    return {
        "reverted_commit": promotion_commit,
        "revert_commit": revert_commit,
        "tag": tag_name,
        "pushed": push,
    }


def cmd_revert(args: argparse.Namespace) -> int:
    try:
        result = revert(repo=args.repo, main_ref=args.main_ref, reason=args.reason, push=args.push)
    except PromotionError as exc:
        print(f"rollback-release: {exc}", file=sys.stderr)
        return 1
    print(f"rollback-release: reverted {result['reverted_commit']} -> {result['revert_commit']}")
    print(f"  tag: {result['tag']}")
    if not result["pushed"]:
        print("  (not pushed -- re-run with --push to make this take effect on origin/main)")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--repo", type=Path, default=REPO, help="repo root (default: this checkout)")
    ap.add_argument("--main-ref", default="origin/main")
    sub = ap.add_subparsers(dest="command", required=True)

    status = sub.add_parser("status", help="show pause state and promotion/rollback history")
    status.set_defaults(func=cmd_status)

    pause = sub.add_parser("pause", help="pause promotion before landing a rollback")
    pause.add_argument("--reason", required=True)
    pause.add_argument("--push", action="store_true")
    pause.set_defaults(func=cmd_pause)

    resume = sub.add_parser("resume", help="resume promotion after a fix is in place")
    resume.add_argument("--push", action="store_true")
    resume.set_defaults(func=cmd_resume)

    revert_p = sub.add_parser("revert", help="revert the most recent promotion commit")
    revert_p.add_argument("--reason", required=True)
    revert_p.add_argument("--push", action="store_true")
    revert_p.set_defaults(func=cmd_revert)

    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
